# daroach.net
#
# VueJS Nuxt Web Server
#
# Author: Gagan Daroach gagandaroach@gmail.com
version: "3"

networks:
  daroachnetwork:
    external: true

services:
  webserver:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=medschooldreams.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=medschooldreams.com
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    networks:
      - daroachnetwork
