# daroach.net
# Nextcloud in Docker with MariaDB storage, Redis accelerator, and Docker cron job.
#
# Author: Gagan Daroach gagandaroach@gmail.com

version: "3"

networks:
  daroachnetwork:
    external: true
  cloud_internal:
    internal: true

services:
  cloud_db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${CLOUD_DATA_DIR}/mariadb:/var/lib/mysql
    env_file:
      - cloud_db.env
      - cloud_db_root.env
    networks:
      - cloud_internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - cloud_internal

  nextcloud:
    build:
      context: .
      dockerfile: Nextcloud.Dockerfile
    restart: always
    volumes:
      - ${CLOUD_DATA_DIR}/nextcloud:/var/www/html
    env_file:
      - cloud_db.env
      - cloud.env
    depends_on:
      - cloud_db
      - redis
    networks:
      - cloud_internal
      - daroachnetwork

  cron:
    image: nextcloud:21-apache
    restart: always
    volumes:
      - ${CLOUD_DATA_DIR}/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - cloud_db
      - redis
    networks:
      - cloud_internal

#  collabora:
#    image: collabora/code
#    expose:
#      - 9980
#    cap_add:
#      - MKNOD
#    environment:
#      - domain=cloud.daroach.net
#      - VIRTUAL_HOST=office.daroach.net
#      - VIRTUAL_NETWORK=daroachnetwork
#      - VIRTUAL_PORT=9980
#      - VIRTUAL_PROTO=https
#      - LETSENCRYPT_HOST=office.daroach.net
#      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
#    networks:
#      - daroachnetwork

