version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: dnet_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webroot:/usr/share/nginx/html

    ports:
      - 10080:80
