# Docker Compose File
# daroach.net environment nuxtjs server
# Author: Gagan Daroach gagandaroach@gmail.com
# Date: April 21 2019

version: "3"

# needed to attach to my servers network
networks:
  daroachnetwork:
    external: true

services:
  nuxt_app_server:
    build: ./dnet_nuxt
    restart: always
    ports: 
      - 3000:3000
    # if you want to use jwilder's nginx proxy container
    env_file: 
       - jwilder_nginx_proxy.env
    # to attach to my servers network
    networks:
       - daroachnetwork
    command:
      "npm run start"
    
