version: '3'
services:
  nginx: 
    build: ./
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
      - ./webroot:/webroot
    ports:
      - 5000:80
