# Docker Compose File
# daroach.net environment
# Author: Gagan Daroach gagandaroach@gmail.com
# Date: April 16 2019

version: "3"

# needed to attach to my servers network
networks:
  daroachnetwork:
    external: true

services:
  vuejs_node_alpine:
    build: ./dnet_vuejs
    restart: always
    ports: 
      - 8080:8080
    # if you want to use jwilder's nginx proxy container
    env_file: 
       - jwilder_nginx_proxy.env
    # to attach to my servers network
    networks:
       - daroachnetwork
    
