version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: dnet_nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ./webroot:/usr/share/nginx/html

    ports:
      - 80:80

# docker-compose up (if need sudo just add $USER to docker group)