#daroach.net Docker Compose File.
# this runs my media collection
#Author: Gagan Daroach
#Date: May 25 2019

version: "3"

networks:
  daroachnetwork:
    external: true
  backend:

services:
  plex:
    image: plexinc/pms-docker
    restart: "unless-stopped"
    ports:
      - 32400:32400/tcp
    environment:
      - VIRTUAL_HOST=media.daroach.net
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=media.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
      - TZ=${TZ}
      - PUID=${MEDIA_PUID}
      - PGID=${MEDIA_PGID}
      - ADVERTISE_IP=https://media.daroach.net/,http://dt49.daroach.lan,https://daroach.net:32400
      - ALLOWED_NETWORKS=10.4.0.0/16
      - PLEX_CLAIM=claim-U3gvTkxaTZz_j5TsFZwv
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${TRANSCODE_CACHE}/:/transcode
      - ${DATA_DIR}:/data
    networks:
      - daroachnetwork
      - backend
  
  deluge:
    image: linuxserver/deluge:latest
    restart: "unless-stopped"
    environment:
      - PUID=${MEDIA_PUID}
      - PGID=${MEDIA_PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/deluge:/config
      - ${TOR_DOWNLOADS}:/downloads
      - ${TOR_WATCH}:/watch
    ports:
      - 8112:8112 # web ui
    networks:
      - backend

  jackett:
    image: linuxserver/jackett:latest
    restart: "unless-stopped"
    networks:
      - backend
    ports:
      - 9117:9117 # web ui
    environment:
      - PUID=${MEDIA_PUID}
      - PGID=${MEDIA_PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TOR_WATCH}:/downloads
      - ${CONFIG_DIR}/jackett:/config

