# daroach.net
#
# VueJS Nuxt Web Server
#
# Author: Gagan Daroach gagandaroach@gmail.com
version: "3"

networks:
  daroachnetwork:
    external: true

services:
  webserver:
    build: ./dnet2
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=daroach.net
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    networks:
      - daroachnetwork
    command: "npm run start"
